/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 factory.gltf 
Author: Alok (https://sketchfab.com/alok.aks50)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bitcoin-factory-voxel-art-d6b36d8c19e841bfb0b6a6e5e033a172
Title: Bitcoin Factory - Voxel art
*/

import React, {useRef, useEffect} from 'react'
import {useGLTF, useAnimations} from '@react-three/drei'
import {Clock, AnimationMixer} from "three";
import {useFrame} from "@react-three/fiber";

const ConverterFactory = (props) => {
    const group = useRef()
    const {nodes, materials, animations} = useGLTF('/factory.gltf')
    const {actions, names} = useAnimations(animations, group)
    console.log(names)

    useEffect(() => {
        actions[names].reset().fadeIn(0.5).play();
    }, []);

    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Sketchfab_Scene">
                <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.015}>
                    <group name="04c4dfbx" rotation={[Math.PI / 2, 0, 0]}>
                        <group name="Object_2">
                            <group name="RootNode">
                                <group name="charecter_1"
                                       position={[-66.25, 81.076, 72.5]} scale={[1, 0.981, 1]}>
                                    <mesh castShadow name="charecter_1_Rez01palette_0"
                                          geometry={nodes.charecter_1_Rez01palette_0.geometry}
                                          material={materials.Rez01palette}/>
                                </group>
                                <group name="BTC01_4"
                                       position={[23.75, 50.025, -100.227]}>
                                    <mesh castShadow name="BTC01_4_Rez01palette_0"
                                          geometry={nodes.BTC01_4_Rez01palette_0.geometry}
                                          material={materials.Rez01palette}/>
                                </group>
                                <group castShadow name="BTC01_3"
                                       position={[23.75, 50.025, -100.227]}>
                                    <mesh name="BTC01_3_Rez01palette_0"
                                          geometry={nodes.BTC01_3_Rez01palette_0.geometry}
                                          material={materials.Rez01palette}/>
                                </group>
                                <group name="BTC01_2"
                                       position={[23.75, 50.025, -100.227]}>
                                    <mesh castShadow name="BTC01_2_Rez01palette_0"
                                          geometry={nodes.BTC01_2_Rez01palette_0.geometry}
                                          material={materials.Rez01palette}/>
                                </group>
                                <group name="BTC01"
                                       position={[23.75, 50.025, -100.227]}>
                                    <mesh castShadow name="BTC01_Rez01palette_0"
                                          geometry={nodes.BTC01_Rez01palette_0.geometry}
                                          material={materials.Rez01palette}/>
                                </group>
                                <group name="BTC00"
                                       position={[25.429, 50.025, 6.403]}>
                                    <mesh castShadow name="BTC00_Rez01palette_0"
                                          geometry={nodes.BTC00_Rez01palette_0.geometry}
                                          material={materials.Rez01palette}/>
                                </group>
                                <group name="BTC0"
                                       position={[26.25, 35, 46.25]}>
                                    <mesh castShadow name="BTC0_Rez01palette_0"
                                          geometry={nodes.BTC0_Rez01palette_0.geometry}
                                          material={materials.Rez01palette}/>
                                </group>
                                <group name="roll01"
                                       position={[-108.75, 53.75, -96.25]}>
                                    <mesh castShadow name="roll01_Rez01palette_0"
                                          geometry={nodes.roll01_Rez01palette_0.geometry}
                                          material={materials.Rez01palette}/>
                                </group>
                                <group name="roll02"
                                       position={[-88.75, 53.75, -96.25]}>
                                    <mesh castShadow name="roll02_Rez01palette_0"
                                          geometry={nodes.roll02_Rez01palette_0.geometry}
                                          material={materials.Rez01palette}/>
                                </group>
                                <group name="Interior_new">
                                    <mesh castShadow name="Interior_new_Rez01palette_0"
                                          geometry={nodes.Interior_new_Rez01palette_0.geometry}
                                          material={materials.Rez01palette}/>
                                </group>
                                <group name="polySurface30">
                                    <mesh castShadow name="polySurface30_Rez01palette_0"
                                          geometry={nodes.polySurface30_Rez01palette_0.geometry}
                                          material={materials.Rez01palette}/>
                                </group>
                                <group name="Null_4" position={[0, 0, -7.4]}>
                                    <group name="money_drop02"
                                           position={[-126.81, 67.506, -92.5]}
                                           rotation={[0, 0, Math.PI / 2]}>
                                        <mesh castShadow name="money_drop02_Rez01palette_0"
                                              geometry={nodes.money_drop02_Rez01palette_0.geometry}
                                              material={materials.Rez01palette}/>
                                    </group>
                                </group>
                                <group name="Null_2" position={[0, 0, -7.4]}>
                                    <group name="money_drop02_2"
                                           position={[-90.982, 65.089, -92.5]}
                                           rotation={[0, 0, Math.PI / 2]}>
                                        <mesh castShadow name="money_drop02_2_Rez01palette_0"
                                              geometry={nodes.money_drop02_2_Rez01palette_0.geometry}
                                              material={materials.Rez01palette}/>
                                    </group>
                                </group>
                                <group name="Null_3"
                                       position={[0, 0, -7.4]}>
                                    <group name="money_drop02_3"
                                           position={[-53.173, 62.498, -92.5]}
                                           rotation={[0, 0, Math.PI / 2]}>
                                        <mesh castShadow name="money_drop02_3_Rez01palette_0"
                                              geometry={nodes.money_drop02_3_Rez01palette_0.geometry}
                                              material={materials.Rez01palette}/>
                                    </group>
                                </group>
                                <group name="Null_1"
                                       position={[0, 0, -7.4]}>
                                    <group name="money_drop02_4"
                                           position={[-15.797, 62.498, -92.5]}
                                           rotation={[0, 0, Math.PI / 2]}>
                                        <mesh castShadow name="money_drop02_4_Rez01palette_0"
                                              geometry={nodes.money_drop02_4_Rez01palette_0.geometry}
                                              material={materials.Rez01palette}/>
                                    </group>
                                </group>
                                <group name="Null">
                                    <group name="money_drop01"
                                           position={[-165.836, 129.574, -92.5]}
                                           rotation={[0, 0, -2.531]}>
                                        <mesh castShadow="true" name="money_drop01_Rez01palette_0"
                                              geometry={nodes.money_drop01_Rez01palette_0.geometry}
                                              material={materials.Rez01palette}/>
                                    </group>
                                </group>
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </group>
    )
}

export default ConverterFactory;

useGLTF.preload('/factory.gltf')
